### ISSUE TITLE
Option to specify which CMake targets to build

### ISSUE THREAD

**Issue by thatbakamono** [chalet-org/chalet#159]
I checked [the documentation](https://www.chalet-work.space/schema/v0.4.0/chalet-json/target-cmake) but didn't find an option to specify which CMake targets to build. Usually a project consists of many (the app/library itself, tests, examples, etc) and many of those are unnecessary to build if we just want to use a library, It would be nice to be able to specify which one we want to build and reference.

**Comment by rewrking** [comment]
Added in [v0.4.1](https://github.com/chalet-org/chalet/releases/tag/v0.4.1)
