### ISSUE TITLE
Native compile strategy: header dependencies

### ISSUE THREAD

**Issue by rewrking** [chalet-org/chalet#16]
No dependency management yet at all. At the moment, the native-experimental strategy is used as the default in CI builds since deps are not needed there, but locally, it's not really a viable option.

The way to do this I think would be to read through all the *.d files and consolidates them to a single list, goes through the list, gets the timestamp for each file, then compares them with the previous timestamp.

MSVC: *.d files have to be parsed from /showIncludes

**Comment by mvladic** [comment]
How about support for vcpkg or Conan?

**Comment by rewrking** [comment]
> 

Poor choice of words in the title -- this is referring to individual cpp file dependency checking in the "native" build strategy (ie. without ninja/makefile behind the scenes).

At the moment, you can invoke vcpkg and Conan with [process targets](https://www.chalet-work.space/docs/creating-targets?id=process-targets), but integration with those isn't really planned. The main issue is getting the toolchain info to the package managers and ensuring they work with the build. vcpkg is probably the most likely of the two to get integrated.
