### ISSUE TITLE
`chalet clean` doesn't remove builds of external dependencies

### ISSUE THREAD

**Issue by thatbakamono** [chalet-org/chalet#161]
As described in the title, `chalet clean` removes all build artifacts related to the main project from the `build/COMPILER_PROFILE` directory (in my case it's `build\x64-pc-windows-msvc17_Release`) but doesn't remove builds of external dependencies

**Comment by rewrking** [comment]
That was intentional originally because it seemed pointless to rebuild the cmake target each time. Would you want to have control over this behavior -- like with a `clean` boolean value?

**Comment by thatbakamono** [comment]
I think it might be sometimes useful to do this, like, when for example something corrupts the build, so yeah, a flag would be awesome.

**Comment by rewrking** [comment]
Fixed in [v0.4.2](https://github.com/chalet-org/chalet/releases/tag/v0.4.2)
