### ISSUE TITLE
IntelliSense or Clangd on windows?

### ISSUE THREAD

**Issue by bitsauce** [chalet-org/chalet#174]
Hi there!

I am really intrigued by this project and wanted to test it out a bit. In my testing, I found that I don't have IntelliSense when editing files (I am using the SDL2 example project). Is IntelliSense or clangd supposed to work on windows in the current version? If this is supported, then it's likely some conflict in my existing settings in VSCode that is causing this.

**Comment by rewrking** [comment]
I haven't dug too deeply into clangd usage inside of VS Code yet (esp on windows), but the standard "C/C++' extension should have intellisense out of the box (also be sure to try out the Chalet extension as well). That's the easiest route.

If you go down the clangd route, you need to generate `compile_commands.json`, which is done with `"generateCompileCommands": true` in `.chaletrc`. You can set it manually in the file or with `chalet --generate-compile-commands configure`. 

From there, you're going to be in some uncharted territory. For instance, Chalet can work with Windows LLVM or MSVC directly (same abi), but at the moment, it will generate compile commands from both, and I don't think it necessarily should with MSVC. If you're using LLVM, it should just work with clangd though. Start with that, and let me know if there are any bugs with the way `compile_commands.json` generates.

**Comment by bitsauce** [comment]
> but the standard "C/C++' extension should have intellisense out of the box
I found out that simply disabling the clangd extension wasn't sufficient, I also had to set `IntelliSense` as the IntelliSense engine in VS code settings. So I got it working now.

However, I do probably prefer to use Clangd when possible, since it is a fair bit more responsive in my experience. So I experimented a bit with your instructions and got `compile_commands.json`. But in order to get clangd to pick up the file I had to add:

```
{
    "clangd.arguments": [
        "--compile-commands-dir=${workspaceFolder}/build/x64-pc-windows-msvc17_Debug",
    ]
}
```

To `.vscode/settings.json`. One issue with this solution is that clangd's suggestion will only update when I build or run the application in Debug. Is there a variable I can use to point clangd to the current output dir? Alternatively, maybe it would be nice to have a config variable that makes Chalet write `compile_commands.json` to the project's root dir, since this is the path that clangd will look for `compile_commands.json` by default.

What do you think?

**Comment by bitsauce** [comment]
> With that said, it looks like the CMake VSCode extension has a setting called `cmake.copyCompileCommands` ...
Cool! Yep, I am actually using that command in my other CMake-based project for this exact reason. Whether or not the `compile_commands.json` should be copied to root I'm not too sure of either. The most important part is to be able to copy it to a consistent location so we can know where to point clangd to

**Comment by rewrking** [comment]
Sorry for the delay on this -- had a bunch of life stuff to deal with. This change is available in version 0.5.0, which you can download here:

https://www.chalet-work.space/download/v0.5.0

**Comment by bitsauce** [comment]
Thanks! I tried testing it out, but it seems like the v0.5.0 installer in that release is actually v0.4.3? Is that the same for you?

**Comment by rewrking** [comment]
Hmm I might have forgotten to update the version in the installer -  I'll fix it later in the evening (EST). It should be 0.5.0 in the executable itself, so just ignore the version in the installer.

**Comment by bitsauce** [comment]
Cool! Just ask one final thing, since the `compile_commands.json` file is written to `build/current`, is it expected for the user to set their compile commands dir to it? E.g. setting:

```json
    "clangd.arguments": [
        "--compile-commands-dir=${workspaceFolder}/build/current",
    ]
```

In `settings.json`? Anyway, it seems to be working well 👍

**Comment by rewrking** [comment]
Yep, that would be expected on the user side - the build system should only provide the `compile_command.json`. Enjoy! Feel free to bring up any thoughts in the [Discussions](https://github.com/chalet-org/chalet/discussions) in the future.

**Comment by rewrking** [comment]
> Thanks! I tried testing it out, but it seems like the v0.5.0 installer in that release is actually v0.4.3? Is that the same for you?

So, yeah, the v0.5.0 release was bungled because it was using the v0.4.x branch instead of 0.5.x or main. I think this change was on it because I was originally going to do a v0.4.4 release.

It's fixed now. All of the new features should be there now (including the right version in the installer):
https://github.com/chalet-org/chalet/releases/download/v0.5.0/chalet-x86_64-pc-windows-msvc-installer.zip

(The other platforms are still building, but Windows is done)
