### ISSUE TITLE
Clang detection on Ubuntu

### ISSUE THREAD

**Issue by bitsauce** [chalet-org/chalet#196]
This is a quality-of-life thing, but I have noticed that `clang` isn't automatically detected when selecting `llvm` on Ubuntu 22.04. When installing clang via `sudo apt install clang-14`, clang will be located at `/usr/bin/clang-14` and `/usr/bin/clang++-14`. It seems to me that Chalet looks for a file called `clang` without any suffix, which makes it so that Clang isn't found unless the user manually creates symlinks to the binaries without the suffixes.

(Another question is also how a developer can choose their desired version of Clang if they have multiple versions installed. But that's maybe accounted for already?)

Thanks!

**Comment by rewrking** [comment]
Great find. The llvm preset doesn't handle prefixes/suffixes (`-14`) yet during detection, so I'll add it.

**Comment by rewrking** [comment]
Fixed in [v0.5.4](https://github.com/chalet-org/chalet/releases/tag/v0.5.4)

`llvm` will still turn up nothing because it doesn't expect any suffix, but `llvm-14` will detect the correct toolchain.

**Comment by bitsauce** [comment]
Great! I just tested it, and it works well from the command line! One thing that would be nice as well is if `llvm-14` was detected by the Chalet extension. As it is now, I have to run `chalet build -t llvm-14` manually once to get that configuration as an option inside VSCode (but that's not a big problem).

**Comment by rewrking** [comment]
See #199. Once the toolchain is global, it can be seen by any project, vscode, `chalet query all-toolchains`, etc. On my Windows machine for instance, I have 3 mingws from msys (11.x - x86, x64 & ucrt x64), 2 standalones (7.x - x86 & x64), TDM (4.8.1 - x86), LLVM 13 in msys (gnu abi, ucrt x64), LLVM 12 standalone (msvc abi)
