### ISSUE TITLE
Architecutre is force set to `auto` when running via the VSCode extension

### ISSUE THREAD

**Issue by bitsauce** [chalet-org/chalet#200]
Based on the discussion from #195, I have tried to copy the local `.chaletrc` to `~/.chalet/config.json` after building once with `llvm-14` and `x86_64-linux-gnu`. When I look at `config.json`, I can confirm that it has its architecture set to `x86_64-linux-gnu`. However, when I run from VSCode, I notice that the generated `.chaletrc` file sets the architecture to `auto`.

I'm not sure what `auto` resolves to, but in my case, I'm getting the same issue where X11 is not detected on Ubuntu.

I have also tried to change the architecture in VSCode via `Command Pallette` -> `Chalet: Change Build Architecture`, but the only option there is `auto`.

Am I doing something wrong here? Thanks!

**Comment by rewrking** [comment]
Yeah, that's a bug in this case. The extension just gets whatever `chalet query` provides and assumes the right architectures are there. In this case, the global architecture of `x86_64-linux-gnu` needs to be provided in these queries and set by the VS Code extension. `llvm-14` also needs to be detected by the query as llvm so it gets the rest of the architectures.

**Comment by rewrking** [comment]
This has been fixed in [v0.5.5](https://github.com/chalet-org/chalet/releases/tag/v0.5.5)

There's also a new Chalet extension version that shows the architecture menu button if the toolchain starts with `llvm-`. Let me know if you run into any more issues!

**Comment by bitsauce** [comment]
I tested it on Ubuntu now; seems to be working well!

**Comment by rewrking** [comment]
Great! I'll close this out.
