### ISSUE TITLE
Issue compiling on macOs

### ISSUE THREAD

**Issue by dimitre** [chalet-org/chalet#230]
Probably my fault here
but I've updated to macOs 12.6.3 and now I have some errors while trying to build chalet latest
it seems something is pointing to the wrong sdk.
Anyway I can download the compiled one and it is working great! Thanks

<img width="1424" alt="Screen Shot 2023-01-30 at 00 47 43" src="https://user-images.githubusercontent.com/58289/215383485-4f0e8ee1-88e7-41b5-939a-9549ca6b45a4.png">

**Comment by rewrking** [comment]
Hmm, the only thing I can think of right now is to try running `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` before building (and clear your build folder). Not sure if I've seen that issue specifically though... I'll try to look into it.

**Comment by dimitre** [comment]
Yeah the command didn't fix. Maybe it is an issue related to CMake installed by brew, which is pointing to 
a non existent path
   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk

**Comment by rewrking** [comment]
Did you update xcode as well?

**Comment by dimitre** [comment]
I've updated macOS but had the latest XCode already installed : Version 14.2 (14C18)

**Comment by rewrking** [comment]
Xcode 14.2 has `MacOSX13.1.sdk`, so I think you just need to remove the old build folder and rebuild from scratch. That doesn't work?

**Comment by dimitre** [comment]
Yes, this fixes everything. Thank you
