### ISSUE TITLE
Homebrew on MacOS

### ISSUE THREAD

**Issue by rewrking** [chalet-org/chalet#242]
100ish stars is prob good enough for Homebrew. What needs to be done to get it in there?

- [ ] Fomula or Cask?
- [ ] Write it
- [ ] Submit it

**Comment by dimitre** [comment]
Cask please. I think this is functional. At least worked well on my system using
```brew install --cask ./chalet.rb```

#### **`chalet.rb`**
```rb
cask "chalet" do
  arch arm: "arm64", intel: "x86_64"

  version "0.5.21"
  sha256 arm:   "5d4220f31c825b88eba2d29924f3911e097e930ec258d05bd8efe16d9f28b23f",
         intel: "1c7241107fe355ce06bf7f366a6f6d0bcf5a602292e97df7e6a81cb837506a43"

  url "https://github.com/chalet-org/chalet/releases/download/v#{version}/chalet-#{arch}-apple-darwin.zip"
  name "Chalet Build Tool"
  desc "A cross-platform project format & build tool for C/C++"
  homepage "https://www.chalet-work.space"

end
```

**Comment by dimitre** [comment]
uploaded to github, so now it is possible to use like this
```
brew install --cask https://raw.githubusercontent.com/dimitre/chalet_homebrew/main/chalet.rb
```

**Comment by rewrking** [comment]
Looked into this a bunch today. I don't totally understand how versioning of casks is done yet in the homebrew-casks repo - for instance, there's an additional `homebrew-cask-versions` repo for "other" versions, wheras the former just has a set version - so is each new version a PR? For now, I'll start adding cask scripts to `scripts/homebrew-cask/(version)` since you can install them easily enough.

Here's the one I added for the current version:

```
brew install --cask https://raw.githubusercontent.com/chalet-org/chalet/main/scripts/homebrew-cask/0.6.5/chalet.rb
```

Also, before I add a cask officially, I need to update the zsh completions to the format described [here](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org) instead of the current bash-style. Homebrew has a path for completions that will need symlinks added.

**Comment by dimitre** [comment]
I'm now using homebrew in this project https://github.com/dimitre/ofbuild
by creating a repo called homebrew-ofbuild I can "tap" in to the brew formula and install using 
```
brew tap dimitre/ofbuild
brew install ofbuild
```

so I can suggest you of creating a repo called https://github.com/chalet-org/homebrew-chalet and put your .rb file inside.
so people will be able to install it via
```
brew tap chalet-org/chalet
brew install chalet
```
and will be easy to upgrade once you publish a new release (I think this can be automated via github actions)

**Comment by dimitre** [comment]
in fact I'm now testing this on dimitre/homebrew-chalet and finding some issues (maybe related to the fact it is a cask)
so unsure of how to proceed

**Comment by rewrking** [comment]
Yeah I'm not sure. The reason why it's setup like it is [now](https://github.com/chalet-org/chalet-homebrew-casks) is because the CI process for a release was kind of a mess at the time, and I did not know how to automate this well. I haven't put out a versioned release in a while, but when I did, I was creating the sha256 by hand.

In the web site, I have a route that stitches them together:
https://github.com/chalet-org/chalet-docs/blob/main/pages/api/brew/%5Bversion%5D/chalet.rb.ts

I'll look into changing this though. I just want to understand how versioning works in brew before doing anything new.

**Comment by rewrking** [comment]
Also of note: right now i have snapshots built from `main`, but no way to install them via brew, so the most recent build you can use via the brew method is v0.7.24.

**Comment by dimitre** [comment]
here is an useful command to calculate sha256 from a download (in my case a zip of sources) 
brew create --set-name ofbuild https://github.com/dimitre/ofbuild/archive/refs/tags/v0.0.6.tar.gz

**Comment by rewrking** [comment]
Okay wow yeah I didn't realize brew basically disabled installing a cask from a url. That must have changed within the past 4 months.

I am still finishing this up (need to update the website and hook this into the ci pipeline), but you can now use:

```sh
brew tap chalet-org/chalet

# standard releases
brew install --cask chalet

# development snapshots
brew install --cask chalet@dev
```
