### ISSUE TITLE
zip compressing and folder structure

### ISSUE THREAD

**Issue by dimitre** [chalet-org/chalet#244]
I'm having an issue with Chalet latest from master (v.6.0)
working with this chalet.json file
https://github.com/dimitre/act/blob/main/chalet.json

when I use chalet bundle
the idea is build assimp library and add to a zip file.

When I decompress the file it recreates the folder strucutre but uncompress the files to the main folder, and maybe other places.
The reconstructed folder is more than 3x the size of the original build folder.

Thank you

**Comment by dimitre** [comment]
Unrelated to the issue, but it would be great to be able to add different libraries to the same zip, and having them in separated folders when uncompressing. not sure if it is already possible. thanks

**Comment by rewrking** [comment]
`"${externalBuild:assimp}/**"` does something subtle that isn't quite what you'd expect: it recursively finds every folder in the assimp build directory and adds it to the include list. Then, when the zip is created, it's plopping anything that in those folders into the root, so it's unnecessarily packing files multiple times. If you remove `/**`, that should be enough, but I have to figure out a smarter way to address it.

> Unrelated to the issue, but it would be great to be able to add different libraries to the same zip, and having them in separated folders when uncompressing. not sure if it is already possible. thanks

Do you just mean to do this?

```json
"include": [
   "${externalBuild:poco}",
   "${externalBuild:assimp}"
]
```

That will make a zip that contains a "poco" and "assimp" folder.
