### ISSUE TITLE
problem with external dependencies

### ISSUE THREAD

**Issue by duhnyel** [chalet-org/chalet#273]
i've been experimenting with using chalet with sdl2 and have encountered this issue and i'd like to know if this is a bug or am i doing something wrong.
So my chalet.json looks like this
`{
	"version": "1.0.0",
	"name": "Chalet Example - SDL",
	"externalDependencies": {
		"sdl": {
			"kind": "git",
			"repository": "https://github.com/libsdl-org/SDL"
		},
		"sdl_image":{
			"kind": "git",
			"repository": "https://github.com/libsdl-org/SDL_image"
		},
		"sdl_ttf":{
			"kind": "git",
			"repository": "https://github.com/libsdl-org/SDL_ttf"
		}
	},
	"abstracts:*": {
		"language": "C++",
		"settings:Cxx": {
			"cppStandard": "c++20",
			"warningsPreset": "strict",
			"includeDirs": [
				"${external:sdl}/include",
				"${external:sdl_image}/include/SDL3",
				"${external:sdl_ttf}/include/SDL3"
			],
			"libDirs": [
				"${external:sdl}/include",
				"${external:sdl_image}/include/SDL3",
				"${external:sdl_ttf}/include/SDL3"
			]
		}
	},
	"targets": {
		"debug":{
			"kind": "executable",
			"settings:Cxx": {
				"precompiledHeader": "src/pch.hpp",
				"includeDirs":[
					"src"
				]
			},
			"files": "src/**.cpp"
		}
	}
}`

if in the inlcudeDirs i have it point to ${external:sdl}/include it does not find the SDL3 library in said folder but if i change it to ${external:sdl}/include/SDL3 it does find the correct files but the SDL can't include the its own libraries bc it looks for the sdl3 folder.

also does chalet have a forum or a discord server to ask questions other than github issues?

**Comment by rewrking** [comment]
The only forum at the moment is in the Discussions section:
https://github.com/chalet-org/chalet/discussions

I haven't tested with SDL 3 yet, but there's an example for an SDL 2 app here:
https://github.com/chalet-org/chalet-example-sdl/blob/main/chalet.json

I imagine 3 is similar - start by changing the `SDL2` in links to `SDL3`.

Interop between SDL and `SDL_image` / `SDL_mixer` / `SDL_ttf` is trickier due to the way they're built from CMake and expect CMake. When I attempted to get `SDL_mixer` to work in my own game engine, I had something like this:

```json
{
	"version": "1.0.0",
	"name": "Chalet Example - SDL",
	"searchPaths": [
		"${externalBuild:sdl_mixer}/external/flac/src/libFLAC",
		"${externalBuild:sdl_mixer}/external/libmodplug",
		"${externalBuild:sdl_mixer}/external/ogg",
		"${externalBuild:sdl_mixer}/external/opus",
		"${externalBuild:sdl_mixer}/external/opusfile"
	],
	"externalDependencies": {
		"sdl": {
			"kind": "git",
			"repository": "git@github.com:libsdl-org/SDL.git",
			"tag": "release-2.26.0"
		},
		"sdl_mixer": {
			"kind": "git",
			"repository": "git@github.com:libsdl-org/SDL_mixer.git",
			"tag": "release-2.6.3",
			"submodules": true
		}
	},
	"abstracts:*": {
		"language": "C++",
		"settings:Cxx": {
			"cppStandard": "c++20",
			"runtimeTypeInformation": false,
			"staticRuntimeLibrary": false,
			"warningsPreset": "strict",
			"treatWarningsAsErrors": true,
			"defines[:debug]": [
				"_DEBUG"
			],
			"includeDirs": [
				"${external:sdl}/include",
				"${external:sdl_mixer}/include"
			],
			"libDirs": [
				"${externalBuild:sdl}",
				"${externalBuild:sdl_mixer}"
			],
			"links[:!debug]": [
				"SDL2",
				"SDL2_mixer"
			],
			"links[:debug]": [
				"SDL2d",
				"SDL2_mixerd"
			],
			"links[:macos]": [
				"iconv"
			],
			"links[:linux]": [
				"dl"
			],
			"links[:windows]": [
				"dwmapi"
			],
			"appleFrameworks": [
				"CoreFoundation",
				"CoreAudio",
				"CoreVideo",
				"CoreHaptics",
				"AppKit",
				"IOKit",
				"Carbon",
				"Metal",
				"AudioToolbox",
				"GameController",
				"ForceFeedback"
			]
		}
	},
	"targets": {
		"sdl": {
			"kind": "cmakeProject",
			"location": "${external:sdl}",
			"recheck": false,
			"rebuild": false,
			"defines[:linux]": [
				"SDL_SHARED=OFF",
				"SDL_STATIC=ON",
				"CMAKE_C_FLAGS=-fPIC"
			],
			"defines[:windows]": [
				"SDL_SHARED=ON",
				"SDL_STATIC=OFF"
			]
		},
		"sdl-mixer": {
			"kind": "cmakeProject",
			"location": "${external:sdl_mixer}",
			"recheck": false,
			"rebuild": false,
			"defines[:macos]": [
				"CMAKE_POSITION_INDEPENDENT_CODE=ON",
				"BUILD_SHARED_LIBS=OFF"
			],
			"defines[:linux]": [
				"CMAKE_POSITION_INDEPENDENT_CODE=ON",
				"BUILD_SHARED_LIBS=OFF"
			],
			"defines[:windows]": [
				"CMAKE_POSITION_INDEPENDENT_CODE=ON",
				"BUILD_SHARED_LIBS=ON"
			],
			"defines": [
				"SDL2MIXER_VENDORED=ON",
				"SDL2MIXER_SAMPLES=OFF",
				"SDL2_INCLUDE_DIR=${cwd}/${external:sdl}/include"
			],
			"defines[:!debug]": [
				"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/libSDL2.a"
			],
			"defines[:debug]": [
				"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/libSDL2d.a"
			],
			"defines[toolchain:pc-windows-msvc+:!debug]": [
				"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/SDL2.lib"
			],
			"defines[toolchain:pc-windows-msvc+:debug]": [
				"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/SDL2d.lib"
			]
		},
		"sdl-app": {
			"kind": "executable",
			"settings:Cxx": {
				"precompiledHeader": "src/PCH.hpp",
				"includeDirs": [
					"src"
				],
				"windowsSubSystem[:!debug]": "windows",
				"windowsApplicationIcon": "platform/windows/app.ico",
				"windowsApplicationManifest": "platform/windows/app.manifest"
			},
			"files": "src/**.cpp"
		}
	},
	"distribution": {
		"SDLApp": {
			"kind": "bundle",
			"buildTargets": "*",
			"macosBundle": {
				"type": "app",
				"infoPropertyList": "platform/macos/Info.plist.json",
				"entitlementsPropertyList": "platform/macos/Entitlements.plist.json",
				"icon": "platform/sdl-logo.png"
			},
			"linuxDesktopEntry": {
				"template": "platform/linux/app.desktop",
				"icon": "platform/sdl-logo.png"
			}
		},
		"SDLApp.dmg": {
			"kind": "macosDiskImage",
			"pathbarVisible": false,
			"textSize": 12,
			"iconSize": 80,
			"background": {
				"1x": "platform/macos/dmg-background.png",
				"2x": "platform/macos/dmg-background@2x.png"
			},
			"size": {
				"width": 512,
				"height": 342
			},
			"positions": {
				"SDLApp": {
					"x": 120,
					"y": 188
				},
				"Applications": {
					"x": 392,
					"y": 188
				}
			}
		}
	}
}
```

The nasty part is this section:

```json
"defines[:!debug]": [
		"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/libSDL2.a"
	],
	"defines[:debug]": [
		"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/libSDL2d.a"
	],
	"defines[toolchain:pc-windows-msvc+:!debug]": [
		"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/SDL2.lib"
	],
	"defines[toolchain:pc-windows-msvc+:debug]": [
		"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/SDL2d.lib"
	]
```

I don't have a great solution for that yet. Instead of just giving SDL_mixer the folder path, you have to explicitly define the library, otherwise it won't find it. It annoyed me to the point where I gave up on SDL_mixer in favor of openal just to simplify the build, 

I imagine `SDL_image` and `SDL_ttf` would be similarly annoying to integrate.

I'll make a branch in the `chalet-example-sdl` project for SDL3 and see if there's any major changes to be aware of. My rule of thumb has been that if a library has an `include` directory followed by its own subdirectory, I use up to the "include" in the build (`includeDirs`), and then `#include <subdirectory/file.h>` in the source code.

**Comment by rewrking** [comment]
This is what I had to change for SDL3:
https://github.com/chalet-org/chalet-example-sdl/commit/732eca33ff9d14f6785588bcf3d2a037a71677a0

**Comment by duhnyel** [comment]
Thanks but this was mainly about making it work at all and not specifically with sdl3 it just happened to be the most recent version of the git repo so the issue with the include folders was the main one

**Comment by rewrking** [comment]
Okay, so did my last paragraph in my first reply answer your question about the include paths or no? You could always start with the example or clone it separately and build that to understand it better.

**Comment by duhnyel** [comment]
yea i think it has but now i'm facing another issue. when i try to add another sdl library it's looking for the libSDL2.a file which the target to build the sdl library didint create so it just throws a bunch of linking errors at me can i just use the libSDL2d.a file which it did create (what are those even for?) or is there some cmake options im not aware of.

heres my chalet.json:

`{
	"version": "1.0.0",
	"name": "Chalet Example - SDL",
	"externalDependencies": {
		"sdl": {
			"kind": "git",
			"repository": "https://github.com/libsdl-org/SDL",
			"tag": "release-2.26.0"
		},
		"sdl_image": {
			"kind": "git",
			"repository": "https://github.com/libsdl-org/SDL_image",
			"branch": "SDL2",
			"submodules": true
		}
	},
	"abstracts:*": {
		"language": "C++",
		"settings:Cxx": {
			"cppStandard": "c++20",
			"runtimeTypeInformation": false,
			"staticRuntimeLibrary": false,
			"warningsPreset": "strict",
			"treatWarningsAsErrors": true,
			"defines[:debug]": [
				"_DEBUG"
			],
			"includeDirs": [
				"${external:sdl}/include",
				"${external:sdl_image}/include"
			],
			"libDirs": [
				"${externalBuild:sdl}",
				"${externalBuild:sdl_image}"
			],
			"links[:!debug]": [
				"SDL2",
				"SDL2_image"
			],
			"links[:debug]": [
				"SDL2d",
				"SDL2_imaged"
			],
			"links[:macos]": [
				"iconv"
			],
			"links[:linux]": [
				"dl"
			],
			"links[:windows]": [
				"dwmapi"
			],
			"appleFrameworks": [
				"CoreFoundation",
				"CoreAudio",
				"CoreVideo",
				"CoreHaptics",
				"AppKit",
				"IOKit",
				"Carbon",
				"Metal",
				"AudioToolbox",
				"GameController",
				"ForceFeedback"
			]
		}
	},
	"targets": {
		"sdl": {
			"kind": "cmakeProject",
			"location": "${external:sdl}",
			"recheck": false,
			"rebuild": false
		},
		"sdl-image": {
			"kind": "cmakeProject",
			"location": "${external:sdl_image}",
			"recheck": false,
			"rebuild": false,
			"defines[:macos]": [
				"CMAKE_POSITION_INDEPENDENT_CODE=ON",
				"BUILD_SHARED_LIBS=OFF"
			],
			"defines[:linux]": [
				"CMAKE_POSITION_INDEPENDENT_CODE=ON",
				"BUILD_SHARED_LIBS=OFF"
			],
			"defines[:windows]": [
				"CMAKE_POSITION_INDEPENDENT_CODE=ON",
				"BUILD_SHARED_LIBS=ON"
			],
			"defines": [
				"SDL2_INCLUDE_DIR=${cwd}/${external:sdl}/include"
			],
			"defines[:!debug]": [
				"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/libSDL2d.a"
			],
			"defines[:debug]": [
				"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/libSDL2d.a"
			],
			"defines[toolchain:pc-windows-msvc+:!debug]": [
				"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/SDL2.lib"
			],
			"defines[toolchain:pc-windows-msvc+:debug]": [
				"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/SDL2d.lib"
			]
		},
		"sdl-app": {
			"kind": "executable",
			"settings:Cxx": {
				"precompiledHeader": "src/pch.hpp",
				"includeDirs": [
					"src"
				],
				"windowsSubSystem[:!debug]": "windows",
				"windowsApplicationIcon": "platform/windows/app.ico",
				"windowsApplicationManifest": "platform/windows/app.manifest"
			},
			"files": "src/**.cpp"
		}
	},
	"distribution": {
		"SDLApp": {
			"kind": "bundle",
			"buildTargets": "*",
			"macosBundle": {
				"type": "app",
				"infoPropertyList": "platform/macos/Info.plist.json",
				"entitlementsPropertyList": "platform/macos/Entitlements.plist.json",
				"icon": "platform/sdl-logo.png"
			},
			"linuxDesktopEntry": {
				"template": "platform/linux/app.desktop",
				"icon": "platform/sdl-logo.png"
			}
		},
		"SDLApp.dmg": {
			"kind": "macosDiskImage",
			"pathbarVisible": false,
			"textSize": 12,
			"iconSize": 80,
			"background": {
				"1x": "platform/macos/dmg-background.png",
				"2x": "platform/macos/dmg-background@2x.png"
			},
			"size": {
				"width": 512,
				"height": 342
			},
			"positions": {
				"SDLApp": {
					"x": 120,
					"y": 188
				},
				"Applications": {
					"x": 392,
					"y": 188
				}
			}
		}
	}
}`

and here's one of the errors:

`/usr/bin/gcc -g  CMakeFiles/showanim.dir/examples/showanim.c.o -o showanim  libSDL2_imaged.a  /home/alyssa/coding/testing/build/x86_64-linux-gnu_Debug/chalet_external/sdl/libSDL2d.a`
(theyre all trigonometric functions but the probably isint related)

**Comment by rewrking** [comment]
Since your building the shared version of SDL2, `SDL2_LIBRARY` needs to reference the .so file:

```json
			"defines[:linux+:!debug]": [
				"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/libSDL2-2.0.so"
			],
			"defines[:linux+:debug]": [
				"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/libSDL2-2.0d.so"
			],
```

You can either replace these lines, or add them afterwards:
```json
			"defines[:!debug]": [
				"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/libSDL2.a"
			],
			"defines[:debug]": [
				"SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/libSDL2d.a"
			],
```

btw, this is where the `SDL2_*` vars are required in SDL_image:
https://github.com/libsdl-org/SDL_image/blob/SDL2/cmake/FindPrivateSDL2.cmake

Also, you'll probably want to set `BUILD_SHARED_LIBS=ON` in SDL_image unless you really want to build that statically.

**Comment by duhnyel** [comment]
Thanks. But the problem I'm having is that when building the sdl library it does not make a file named libsdl2.a or the .so equivalent.

So what I'm trying to figure out is that is there another file I could use instead of libsdl2.a or is there something wrong with my chalet config

The files currently present after statically building sdl are:

**Comment by duhnyel** [comment]
Thanks. But the problem I'm having is that when building the sdl library it does not output the libsdl2.a file.

So is there a substitute I could use or is there just some build options I've missed

The libraries outputted by chalet:
libSDL2_test.a
libSDL2d.a
libSDL2maind.a

Also what's the difference between the regular libsdl2 file and the libsdl2d file?

**Comment by rewrking** [comment]
`d` is the suffix SDL uses for the debug version, so the release version is `libSDL2.a`, and the debug version is `libSDL2d.a` (same pattern with the .so files). The debug version has debugging symbols so you can step through the SDL library in a debugger.

This specifically, is wrong because `:!debug` means "not debug", so it should be the release version (without the d suffix) 
```json
"defines[:!debug]": [
   "SDL2_LIBRARY=${cwd}/${externalBuild:sdl}/libSDL2d.a"
],
```

**Comment by duhnyel** [comment]
Thanks again but the problem I'm having is that building the sdl2 lib does not output a libsdl2.a file it only outputs these:

libSDL2_test.a
libSDL2d.a
libSDL2maind.a

**Comment by rewrking** [comment]
`chalet -c Release build` should produce `libSDL2.a` within build/*_Release/chalet_external/sdl
`chalet -c Debug build` should produce `libSDL2d.a` within build/*_Debug/chalet_external/sdl

You're generally going to working with the Debug build, but when you want to distribute your app, you want the Release build. That part is clear, yes? That should inform the decisions you make to build your app in `chalet.json`.

**Comment by duhnyel** [comment]
thank you. turns out thats not the problem im getting theese errors:

`[25/26] Linking C executable showanim
FAILED: showanim 
: && /usr/bin/gcc -g  CMakeFiles/showanim.dir/showanim.c.o -o showanim  libSDL2_imaged.a  /home/alyssa/coding/testing/build/x86_64-linux-gnu_Debug/chalet_external/sdl/libSDL2d.a && :
/usr/bin/ld: /home/alyssa/coding/testing/build/x86_64-linux-gnu_Debug/chalet_external/sdl/libSDL2d.a(SDL_stdlib.c.o): in function `SDL_atan_REAL':
/home/alyssa/coding/testing/chalet_external/sdl/src/stdlib/SDL_stdlib.c:38: undefined reference to 'atan'
/usr/bin/ld: /home/alyssa/coding/testing/build/x86_64-linux-gnu_Debug/chalet_external/sdl/libSDL2d.a(SDL_stdlib.c.o)`

and errors like this continue with a bunch of other trigonometric functions

**Comment by rewrking** [comment]
Change `"rebuild": false` to `"rebuild": true` and run `chalet rebuild`. I'm curious if that makes a difference. I was able to build this in Ubuntu/WSL from the chalet.json you sent a few posts up.

**Comment by duhnyel** [comment]
it didint work and i also tried removing the sdl package installed by the package managen

**Comment by rewrking** [comment]
Not sure where you landed with this, but the [latest version](https://github.com/chalet-org/chalet/releases/tag/v0.7.0) should handle a lot of the build path issues you were probably hitting. If you start with the [SDL example](https://github.com/chalet-org/chalet-example-sdl), you should not need to get SDL from your OS' package manager. It's built from source. Start with a clean build, and add to it from there.
