### ISSUE TITLE
CHATLET issue

### ISSUE THREAD

**Issue by KaeliseB** [chalet-org/chalet#327]
So this has been going on for like, 2 months, and so the problem is that whenever I try to join ANY type of Chatlet room either I make or somebody else makes, my screen just turns WHITE!, I've tried refreshing, don't work, I tried resetting my computer, STILL DOESN'T WORK! I've tried to close and open my computer while on the tab, Did not work either!
![Screenshot 2023-11-29 8 09 34 PM](https://github.com/chalet-org/chalet/assets/152455571/f83f7bf6-a758-4983-95a8-0ad66f96a96d)

**Comment by rewrking** [comment]
Wrong repo.
