### ISSUE TITLE
MSVC C++20 modules: support compile_commands.json

### ISSUE THREAD

**Issue by HerrNamenlos123** [chalet-org/chalet#342]
Hey.... sorry for seemingly spamming issues here, but somehow things just don't work out...

My issue is that i want to work in Neovim, which needs a compile_commands.json for LSP, and i get errors all over the place. I found out that I can pass `--generate-compile-commands` to chalet, which per documentation should generate it inside the build folder, but it is nowhere to be found.

EDIT:
I realized it is actually always generated by default in a new project, but it is not when C++20 Modules are enabled. Not even when specifying the flag. Why would that be? Could that be changed?

**Comment by rewrking** [comment]
Yeah that's correct. compile_commands.json hasn't been implemented with C++20 modules yet because intellisense for it inside Visual Studio only works sometimes. so I'm not even sure what's possible with LSP and MSVC.

**Comment by HerrNamenlos123** [comment]
Well, i mean it's not just that it complains, but it has errors because it cannot find the header locations, etc., so the content of compile_commands.json is actually necessary for it to find the files.

I am now simply working without modules. Not a huge thing, but it would have been interesting to try. Without modules, and the generated compile_commands, i get full code completion.

**Comment by rewrking** [comment]
That's fair. With clangd, you can give it an empty `compile_commands.json` and I think it kind of just ignores the file you're working in. If LSP was the same, I'd add a short-term fix to generate that stub now.

**Comment by rewrking** [comment]
I have a fix for this as well that will generate the compile_commands.json for modules and header units.

**Comment by rewrking** [comment]
Available in [v0.7.8](https://github.com/chalet-org/chalet/releases/tag/v0.7.8)

**Comment by HerrNamenlos123** [comment]
compile_commands.json is now generated and LSP works in a solution that uses C++23 and modules. Thank you very much!
