### ISSUE TITLE
Typo in CLI output (and possible enhancement)

### ISSUE THREAD

**Issue by HerrNamenlos123** [chalet-org/chalet#343]
I noticed a very simple typo in the output when you output to a Visual Studio solution.
![grafik](https://github.com/chalet-org/chalet/assets/44909261/37a9edb4-b23a-4af4-b565-45e4294451ff)

It says `Ouptut` instead of `Output`. Should be an easy fix :)

What would you think about the option that once the .sln file is generated, it asks you if Visual Studio should be opened right now?
This would involve a simple yes/no question and executing `start .../build/.vssolution/chalet-test.sln`. Then you could write `chalet export vssolution` and press enter twice, and VS opens.

**Comment by rewrking** [comment]
Ah, can't believe I didn't catch that. It'll be fixed.

As for opening the solution - definitely thought about doing something like that. On macos in iTerm2, you can ctrl+click the xcode project filename and launch it, and it's been an annoyance not being able to do that in the Windows terminal for VS projects. Your suggestion would introduce user input in a command other than `init`, which I'm not too keen on. Would an extra option like `--launch` suffice?

**Comment by HerrNamenlos123** [comment]
I see. Hm, I'm not too impressed by a commandline option nobody is likely to know about. If you go that route, I think it should at least be written to the terminal. I think the output could say `To open Visual Studio, re-run the command with 'chalet export vssolution --open' `, or it could simply say `To open VS, run: start build/.vssolution/chalet-test.sln`. Either way, it should be plainly obvious that this is a thing.

**Comment by HerrNamenlos123** [comment]
I am fine with both, but I think having `--open` would be great, because when you export for the first time you see this and remember it, and when you use VS export for at least a few times, you start to remember it and always add `--open`. Simply suggesting the command would mean you always have to manually type or paste it, even if you would be congnitively able to remember a `--open` flag. I will leave it up to you.

**Comment by rewrking** [comment]
That is fair. This is actually a similar problem as profiling. Right now, `chalet -c Profile buildrun` will launch the `.vsp` in VS after the program has been run, and that action has a cli option for `--launch-profiler` and defaults to true.

I realize that `--open` may not be obvious right away, but opening VS is not something you'll always be doing. For instance, if you already have VS open and need to re-export the project after making chalet.json changes, you could run the command again and VS will pick up the changes and refresh itself. Adding the extra steps for user input in that case would slow that workflow down. I think `--open` is a reasonable compromise because users will see it in `chalet export --help`, and it fits into the same design as launching a profiler.

**Comment by HerrNamenlos123** [comment]
Yep i am actually completely fine with ` --open`

**Comment by rewrking** [comment]
Alright. This is officially done. It's available in [v0.7.9](https://github.com/chalet-org/chalet/releases/tag/v0.7.9).

With `--open`, the IDE/editor should launch as a separate process (freeing up the terminal essentially). Let me know if you have any issues with it.

**Comment by HerrNamenlos123** [comment]
This works perfectly. Thank you so much for the effort, I really appreciate it.

![grafik](https://github.com/chalet-org/chalet/assets/44909261/ddf42c2f-1a8f-4501-b5e6-916cb747d171)

Just a minor side note: Do you think it would make sense to add a simple hint if `--open` is not used, so that the user realizes that this is a thing? I don't think it would have any negative impact as it's just an additional line printed. It could say : `Hint: Use ' --open'  next time to open the Visual Studio project` (or other IDEs that support --open)

Just an idea to make the flag more accessible to new users, while not bothering experienced users. The flag itself already works perfectly, thanks.

**Comment by rewrking** [comment]
The note has been added to [v0.7.10](https://github.com/chalet-org/chalet/releases/tag/v0.7.10). It should look like this:


![note](https://github.com/chalet-org/chalet/assets/4885461/d3dcc19b-6363-46ba-a17d-10be8ff3d23c)

**Comment by HerrNamenlos123** [comment]
Perfect, exactly like I imagined it. I love it! Thank you very much!
Haven't tested it yet but i'm gonna assume the message is printed, so i'm closing the issue
